### ISSUE TITLE
export CHPL_LIBMODE=shared

### ISSUE THREAD

**Issue by ben-albrecht** [krishnadey30/jupyter_kernel_chapel#1]
```bash
export CHPL_LIBMODE=shared
```

should be

```bash
export CHPL_LIB_PIC=shared
```

This setting was switched to `CHPL_LIB_PIC=pic` in Chapel 1.18. See the [compiling Chapel as a library docs](https://chapel-lang.org/docs/master/technotes/libraries.html#static-and-dynamic-libraries) for more info.

**Comment by krishnadey30** [comment]
@ben-albrecht  Thanks for reminding. I will implement it once and update the documentation.

**Comment by krishnadey30** [comment]
@ben-albrecht  I have updated the documentation. 
Closing the issue.
