### ISSUE TITLE
Host on PyPI

### ISSUE THREAD

**Issue by ben-albrecht** [krishnadey30/jupyter_kernel_chapel#2]
Is it possible to host this as a pip package on PyPI so that a user can pip install it and it will be available to their Jupyter notebook kernels?

A quick pip search reveals existing kernels that do something like this:

```
coq-jupyter (1.4.0)                          - Coq kernel for Jupyter
jupyter-sql (0.1.0)                          - Simple SQL kernel for Jupyter
jupyter-kernel-singular (0.9.8)              - A Jupyter kernel for singular
jupyter-kernel-polymake (0.16)               - A Jupyter kernel for polymake
macaulay2-jupyter-kernel (0.6.7)             - Jupyter kernel for Macaulay2
jupyter-kernel-gap (0.15)                    - A Jupyter kernel for GAP
jupyter-fortran-kernel (0.1.0)               - Minimalistic Fortran kernel for Jupyter
sorna-jupyter-kernel (0.1.3)                 - Sorna Jupyter Kernel Integration
jupyter-kernel-mgmt (0.3.0)                  - Jupyter protocol implementation and client libraries
```

Clearly, there is not a standardized naming scheme. However, `jupyter-kernel-chapel` seems like the most popular option.

**Comment by krishnadey30** [comment]
@ben-albrecht I will host it in pip.

**Comment by krishnadey30** [comment]
@ben-albrecht I have hosted it in PyPI. 
For installing you can follow the readme or
```bash
pip3 install jupyter-kernel-chapel
install_chapel_kernel --user
```

**Comment by ben-albrecht** [comment]
Nice! Is it possible for the `setup.py` to do the `install_chapel_kernel` step automatically or is it separate for a specific reason? 

Taking a glance at the [fortran kernel repository](https://github.com/ZedThree/jupyter-fortran-kernel), it looks like they require a similar post-installation command: `jupyter-kernelspec install fortran_spec/`.

 Perhaps this is the norm for installing kernels?

**Comment by krishnadey30** [comment]
Hey @ben-albrecht, Actually we are doing it internally rather than asking the user to do that 
https://github.com/krishnadey30/jupyter_kernel_chapel/blob/ce54fb7eedc3de9d853890e7908971f9b5ebbb55/jupyter-kernel-chapel/install_chapel_kernel#L33
But if you will check fortran is using [json file](https://github.com/ZedThree/jupyter-fortran-kernel/blob/master/fortran_spec/kernel.json) and calling it from outside to install it.

**Comment by ben-albrecht** [comment]
> Actually we are doing it internally rather than asking the user to do that

Oh, so can a user skip this step?

```
> install_chapel_kernel --user
```

I'll try it out myself when I get a chance.

**Comment by krishnadey30** [comment]
@ben-albrecht No, I don't think so. 
But I will try to find out some other ways for this.

**Comment by krishnadey30** [comment]
@ben-albrecht  I have made changes and now 
```bash
> install_chapel_kernel --user
```
is not needed.

**Comment by ben-albrecht** [comment]
That worked for me! Thanks!
