### ISSUE TITLE
Add Chapel logo to kernel menu

### ISSUE THREAD

**Issue by ben-albrecht** [krishnadey30/jupyter_kernel_chapel#5]
Currently, Chapel shows up in the jupyter notebook kernels with a generic "C" logo:

![Screen Shot 2019-03-27 at 10 28 02 AM](https://user-images.githubusercontent.com/3595449/55084239-462c0400-507b-11e9-93cc-3dc97b7a5f70.png)

It would be nice to have the Chapel logo instead:

![symbol](https://user-images.githubusercontent.com/3595449/55084798-ed10a000-507b-11e9-8785-61217fa297c6.png)

**Comment by krishnadey30** [comment]
@ben-albrecht I have updated the logo.

**Comment by krishnadey30** [comment]
![image](https://user-images.githubusercontent.com/22263782/55520583-a255e000-569a-11e9-81c1-1b113b5c4cfc.png)
This is how logo is looking.

**Comment by ben-albrecht** [comment]
Very cool!
